- name: Save and Commit Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # משיכת שינויים אחרונים כדי למנוע התנגשות
          git pull origin main --rebase
          
          git add fleet_db.json
          # בדיקה אם יש בכלל מה לעדכן
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update fleet data [skip ci]"
            git push origin main
          fi
